site_name: FastAPI Tortoise
nav:
  - Get started: index.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite

repo_name: 'chaotism/fastapi-purser'
repo_url: 'https://github.com/chaotism/fastapi-purser/'